FROM maven:3.6.3-jdk-8 AS build

WORKDIR /app

RUN git clone https://github.com/kkenan/basic-microservices.git

WORKDIR /app/basic-microservices/spring-boot-app

RUN mvn clean package -DskipTests

FROM openjdk:8-jre-alpine

WORKDIR /app

COPY --from=build /app/basic-microservices/spring-boot-app/target/spring-boot-app-1.0-SNAPSHOT.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
